[project]
name = "votify"
version = "1.6"
description = "A command-line app for downloading songs, podcasts and videos from Spotify."
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"
dependencies = [
    "click>=8.3.1",
    "colorama>=0.4.6",
    "inquirerpy>=0.3.4",
    "mutagen>=1.47.0",
    "pillow>=12.1.0",
    "protobuf>=6.33.5",
    "pybase62>=1.0.0",
    "pycryptodome>=3.23.0",
    "pywidevine>=1.9.0",
    "websocket-client>=1.9.0",
    "yt-dlp>=2026.2.4",
]

[project.urls]
repository = "https://github.com/glomatico/votify"

[project.scripts]
votify = "votify.cli:main"
