[project]
name = "votify"
description = "A Python CLI app for downloading songs, podcasts and videos from Spotify."
requires-python = ">=3.10"
authors = [{ name = "glomatico" }]
dependencies = [
    "click",
    "colorama",
    "inquirerpy",
    "mutagen",
    "pillow",
    "protobuf",
    "pybase62",
    "pycryptodome",
    "pywidevine",
    "yt-dlp",
]
readme = "README.md"
dynamic = ["version"]

[project.urls]
repository = "https://github.com/glomatico/votify"

[build-system]
requires = ["flit_core"]
build-backend = "flit_core.buildapi"

[project.scripts]
votify = "votify.cli:main"
