[project]
name = "votify"
description = "A Python CLI app for downloading songs/podcasts from Spotify in Vorbis (OGG)."
requires-python = ">=3.8"
authors = [{ name = "glomatico" }]
dependencies = [
    "click",
    "pillow",
    "protobuf",
    "pybase62",
    "pycryptodome",
    "yt-dlp",
]
readme = "README.md"
dynamic = ["version"]

[project.urls]
repository = "https://github.com/glomatico/votify"

[build-system]
requires = ["flit_core"]
build-backend = "flit_core.buildapi"

[project.scripts]
votify = "votify.cli:main"
